spring:
  datasource:
    url: jdbc:mysql://服务器地址:3306/risk_management?useSSL=false&useCursorFetch=true&defaultFetchSize=1000
    username: 用户名
    password: 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 2000
      minimum-idle: 10

  redis:
    # 哨兵模式
    sentinel:
      master: sentinel-10.16.34.125-6390
      nodes:
        - 10.16.34.125:6392
        - 10.16.34.125:6393
        - 10.16.34.125:6394

    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 9
        # 连接池中的最小空闲连接
        min-idle: 0
        # Redis数据库索引(默认为0)
      database: 0
      # 连接超时时间（毫秒）
      timeout: 60000
